name: 'march'
datapath: 'D:\final_data\Dataset\March2013\key_graph_norm'
pin_memory: True
adaptive_loader: False
is_directed: False
is_multiclass: True  # True for multi-class generation
node_jitter: True  # Turns off node position augmentation for node diffusion
