defaults:
    - _self_
    - general : general_default
    - model : discrete_cow
    - train : train_default
    - dataset : cow  # top_cow


hydra:
  job:
    chdir: True
  run:
    dir: ./logs/cow${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}

